#!/bin/bash --login
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -t 08:00:00
#SBATCH -J BWA_serum
#SBATCH -p core
#SBATCH -n 2

#load module tools

module load bioinfo-tools
module load bwa
module load samtools

#Create a index with the efaecium.contigs.fasta file and name it has genome.fa
bwa index genome.fa

#Start BWA with the reference and sample genome
bwa mem genome.fa trim_paired_ERR1797969_pass_1.fastq.gz trim_paired_ERR1797969_pass_2.fastq.gz > ERR1797969_serum_paired.sam 

#Create .sam files into 1 .bam file

samtools view -S -b ERR1797969_serum_paired.sam > ERR1797969_paired_serum.bam

# sort the .bam file

samtools sort ERR1797969_paired_serum.bam -o ERR1797969_sorted_serum.bam  
