#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10:00:00
#SBATCH -J test_phix

cat $0
echo JOB = $SLUM_JOBID

#importing modules
module load bioinfo-tools
module load bowtie2
module load samtools
module load bcftools

#copying input data
cp /proj/uppmax2021-2-3/ngs/phix/*.fq $SNIC_TMP/

cd $SNIC_TMP
mkdir bow_genome
#copying references
cp /sw/data/igenomes/PhiX/Illumina/RTA/Sequence/Bowtie2Index/* $SNIC_TMP/bow_genome/ #Copy whole folder.
ls bow_genome/
cp /sw/data/igenomes/PhiX/Illumina/RTA/Sequence/WholeGenomeFasta/genome.fa $SNIC_TMP/bcf_genome.fa
cp /sw/data/igenomes/PhiX/Illumina/RTA/Sequence/WholeGenomeFasta/genome.fa.fai $SNIC_TMP/bcf_genome.fai


#cd into workspace

#Setting ref vars
export BOW_REF=bow_genome/genome
export BCF_REF=bcf_genome.fa

#Align, sort, index, and convert each file

for f in *.fq
do
	export FILE=${f%.*} # %.* to only match filename and variable to make it less ugly.
	bowtie2 -x ${BOW_REF%.*} -U $FILE.fq -S $FILE.sam 
	samtools sort $FILE.sam -o $FILE.bam
	samtools index $FILE.bam 
	bcftools mpileup -f $BCF_REF $FILE.bam | bcftools call -mv -Ob -o $FILE.bcf
	bcftools view $FILE.bcf -o $FILE.vcf
done

 
cp *.out ~/logs/
