#!/bin/bash --login
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -t 08:00:00
#SBATCH -J htseq_BH
#SBATCH -p core
#SBATCH -n 2

#load module tools

module load bioinfo-tools
module load htseq
module load samtools

samtools index ERR1797972_sorted_BH.bam

# Start htseq
#Use the sorted .bam files
# Have the output in a .txt file due to space

htseq-count -r pos -t CDS -i locus_tag -f bam ERR1797972_sorted_BH.bam efaecium_trimmed.gff > htseqERR1797972.txt
