#!/bin/bash --login
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -t 08:00:00
#SBATCH -J BWA2
#SBATCH -p core
#SBATCH -n 2

#load module tools

module load bioinfo-tools
module load bwa

#Create a index with the efaecium.contigs.fasta file and name it as genome.fa
bwa index genome.fa

#Start BWA with the index and trimmed fastq.gz files
bwa mem genome.fa trim_paired_ERR1797973_pass_1.fastq.gz trim_paired_ERR1797973_pass_2.fastq.gz > ERR1797973_paired.bam 


