#!/bin/bash --login
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -t 08:00:00
#SBATCH -J Serum3_BWA
#SBATCH -p core
#SBATCH -n 2

#load module tools

module load bioinfo-tools
module load bwa
module load samtools

#Start BWA
#Create a index with the efaecium.contigs.fasta file and name it has genome.fa
bwa index genome.fa

#Start BWA with the reference and sample 
bwa mem genome.fa trim_paired_ERR1797971_pass_1.fastq.gz trim_paired_ERR1797971_pass_2.fastq.gz > ERR1797971_serum_paired.sam 

#Create .sam files into 1 .bam file

samtools view -S -b ERR1797971_serum_paired.sam > ERR1797971_serum_paired.bam

# sort the .bam file

samtools sort ERR1797971_serum_paired.bam -o ERR1797971_serum_sorted.bam
